export const AURAS = [
  { id: "none", name: "None", how: "", group: "rank" },
  { id: "ember", name: "Ember", how: "Any lift at D", tier: 1, group: "rank", colors: ["#FF9340", "#FF4D6D"] },
  { id: "tide", name: "Tide", how: "Any lift at C", tier: 2, group: "rank", colors: ["#38C6FF", "#2F6BFF"] },
  { id: "storm", name: "Storm", how: "Any lift at B", tier: 3, group: "rank", colors: ["#B14BFF", "#38C6FF"] },
  { id: "inferno", name: "Inferno", how: "Any lift at A", tier: 4, group: "rank", colors: ["#7DD3FC", "#FFFFFF"] },
  { id: "halo", name: "Halo", how: "Any lift at S", tier: 5, group: "rank", colors: ["#FFD447", "#FFFFFF"] },
  { id: "godray", name: "Godray", how: "Any lift at SS", tier: 6, group: "rank", colors: ["#FFFFFF", "#7DF9FF"] },
  { id: "smolder", name: "Smoldering Ember", how: "Train 30 days in a row", task: "streak30", group: "feat", colors: ["#FF6A2B", "#7A1E0E"] },
  { id: "stormborn", name: "Stormborn", how: "Log a run in rain, snow, or 40°F and below", task: "weatherRun", group: "feat", colors: ["#8FB8FF", "#E6F0FF"] },
  { id: "dawn", name: "Dawnbreaker", how: "Start a workout between 4 and 6 AM", task: "dawn", group: "feat", colors: ["#FF8A5B", "#FFD36B"] },
  { id: "wanderer", name: "Wanderer", how: "10,000 steps a day, 7 days in a row", task: "steps7", group: "feat", colors: ["#7BC96F", "#E0B872"] },
  { id: "standardbearer", name: "Standard-Bearer", how: "Clear 10 crew raids", task: "raids10", group: "feat", colors: ["#C2001F", "#E8C56A"] },
  { id: "atlas", name: "Atlas", how: "Iron Mover III achievement — 1,000,000 lb lifetime", ach: "volume-2", group: "feat", colors: ["#C9CDD4", "#6B7280"] },
  { id: "forge", name: "Forge", how: "Unbroken III achievement — 100-day streak", ach: "streak-2", group: "feat", colors: ["#FFB43C", "#FF5A1F"] },
  { id: "wyrm", name: "Wyrmfire", how: "Defeat the Iron Wyrm", loot: "wyrm", group: "boss", colors: ["#3DF08A", "#FFD447"] },
  { id: "frost", name: "Frostbite", how: "Defeat the Frost Colossus", loot: "colossus", group: "boss", colors: ["#B3ECFF", "#FFFFFF"] },
  { id: "abyss", name: "Abyss", how: "Defeat the Gravemaw", loot: "gravemaw", group: "boss", colors: ["#6A00FF", "#FF2D6F"] },
  { id: "chud", name: "Chud", how: "Defeat the Chud King", loot: "chud", group: "boss", colors: ["#FFB43C", "#8BC34A"] },
  { id: "rust", name: "Rustfall", how: "Defeat the Rust Titan", loot: "rust", group: "boss", colors: ["#C7743A", "#6B3A1E"] },
  { id: "thunder", name: "Thunderhead", how: "Defeat the Stormcaller Harpy", loot: "harpy", group: "boss", colors: ["#7DD3FC", "#FFF27A"] },
  { id: "hollow", name: "Hollow Steel", how: "Defeat the Hollow Warden", loot: "warden", group: "boss", colors: ["#9AA7BD", "#FFFFFF"] },
  { id: "deep", name: "The Deep", how: "Defeat the Leviathan", loot: "leviathan", group: "boss", colors: ["#2F6BFF", "#00D9FF"] },
  { id: "magma", name: "Magma", how: "Defeat the Molten Behemoth", loot: "behemoth", group: "boss", colors: ["#FF5A1F", "#FFD447"] },
  { id: "plague", name: "Plague", how: "Defeat the Plague Rat Lord", loot: "ratlord", group: "boss", colors: ["#8BC34A", "#3E5F1A"] },
  { id: "sand", name: "Sandstorm", how: "Defeat the Sandstorm Pharaoh", loot: "pharaoh", group: "boss", colors: ["#E8C872", "#B8860B"] },
  { id: "void", name: "Void", how: "Defeat the Void Sovereign", loot: "void", group: "boss", colors: ["#6A00FF", "#000000"] },
  { id: "yogurt", name: "Yogurt", how: "Yogurt Male achievement (100 yogurts)", ach: "yogurt-0", group: "special", colors: ["#FFF8E7", "#F1DDB5"] },
  { id: "champion", name: "Champion", how: "Win a season", season: true, group: "special", colors: ["#FFD447", "#FF9340"] },
  { id: "vendetta", name: "Vendetta", how: "Beat your Nemesis in 5 duels", nemesis: 5, group: "special", colors: ["#FF1F4B", "#3A0010"] },
  { id: "ascended", name: "Ascended", how: "Reigning #1 on the season board", reigning: true, group: "special", colors: ["#FFD447", "#7DF9FF"] },
  { id: "huntersmoon", name: "Hunter's Moon", how: "Land the killing blow on a global boss", worldFirst: true, group: "special", colors: ["#C2001F", "#E4E8F2"] },
  { id: "wheel", name: "Living Wheel", how: "Finish #1 two seasons in a row", seraph: true, group: "special", colors: ["#38C6FF", "#FFD447"] },
  { id: "soon_throne", name: "Throne", how: "Coming soon", soon: true, group: "soon", colors: ["#C9A8FF", "#7DF9FF"] },
  { id: "soon_seraphim", name: "Seraphim", how: "Coming soon", soon: true, group: "soon", colors: ["#FFFFFF", "#FFD447"] },
  { id: "sigil", name: "Spirit Spark", how: "Anime Crate · uncommon · embers that refuse to fade", crate: true, group: "crate", rarity: "uncommon", ptsMult: 0.03, colors: ["#FFB86B", "#FFD447"] },
  { id: "steadybreath", name: "Steady Breath", how: "Anime Crate · uncommon · stillness under pressure", crate: true, group: "crate", rarity: "uncommon", ptsMult: 0.02, colors: ["#DFFBFF", "#7DF9FF"] },
  { id: "iaidraw", name: "Iai Draw", how: "Anime Crate · uncommon · silence, then one perfect line", crate: true, group: "crate", rarity: "uncommon", ptsMult: 0.02, colors: ["#FFFFFF", "#38C6FF"] },
  { id: "glassfire", name: "Cursed Ember", how: "Anime Crate · epic · violet fire at the edge", crate: true, group: "crate", rarity: "epic", ptsMult: 0.05, colors: ["#a855f7", "#ec4899"] },
  { id: "stormstep", name: "Stormstep", how: "Anime Crate · epic · thunder without warning", crate: true, group: "crate", rarity: "epic", ptsMult: 0.05, colors: ["#FFFFFF", "#7DD3FC"] },
  { id: "zeropoint", name: "Zero Point", how: "Anime Crate · epic · the air freezes first", crate: true, group: "crate", rarity: "epic", ptsMult: 0.05, colors: ["#DDF6FF", "#7DF9FF"] },
  { id: "ninetail", name: "Ninetail", how: "Anime Crate · epic · nine flames answer as one", crate: true, group: "crate", rarity: "epic", ptsMult: 0.05, colors: ["#FF9340", "#FFD447"] },
  { id: "ironbound", name: "Ironbound", how: "Anime Crate · epic · the chains remember every rep", crate: true, group: "crate", rarity: "epic", ptsMult: 0.05, colors: ["#9AA7BD", "#5B6472"] },
  { id: "crownfall", name: "Redline", how: "Anime Crate · legendary · power beyond the gauge", crate: true, group: "crate", rarity: "legendary", ptsMult: 0.08, colors: ["#C2001F", "#FFD447"] },
  { id: "ledger", name: "The Ledger", how: "Anime Crate · legendary · every debt is written", crate: true, group: "crate", rarity: "legendary", ptsMult: 0.08, colors: ["#161616", "#C2001F"] },
  { id: "bonewright", name: "Bonewright", how: "Anime Crate · legendary · pressure makes armour", crate: true, group: "crate", rarity: "legendary", ptsMult: 0.08, colors: ["#F4EAD2", "#FFDFA3"] },
  { id: "ossuary", name: "Ossuary", how: "Anime Crate · legendary · built from everything that broke before you", crate: true, group: "crate", rarity: "legendary", ptsMult: 0.08, colors: ["#E8E0CC", "#7CE8A8"] },
  { id: "nullpoint", name: "Nullpoint", how: "Anime Crate · mythic · motion ends at the shell", crate: true, group: "crate", rarity: "mythic", ptsMult: 0.1, colors: ["#a855f7", "#ec4899"] },
  { id: "carve", name: "Carve", how: "Anime Crate · mythic · the frame remembers every cut", crate: true, group: "crate", rarity: "mythic", ptsMult: 0.1, colors: ["#ec4899", "#fff"] },
  { id: "brandmark", name: "Brandmark", how: "Anime Crate · mythic · one mark outlasts iron", crate: true, group: "crate", rarity: "mythic", ptsMult: 0.1, colors: ["#a855f7", "#fff"] },
  { id: "fallenlight", name: "Fallen Light", how: "Anime Crate · mythic · the halo broke on the way down", crate: true, group: "crate", rarity: "mythic", ptsMult: 0.1, colors: ["#E8C878", "#C0453A"] },
  { id: "eclipseheart", name: "Eclipseheart", how: "Anime Crate · gilded · the old sun still burns", crate: true, group: "crate", rarity: "gilded", gilded: true, ptsMult: 0.12, colors: ["#E8C56A", "#FFF6C9"] },
  { id: "blacksun", name: "Black Sun", how: "Secret — undiscovered", crate: true, group: "crate", rarity: "secret", ptsMult: 0.15, colors: ["#FFFFFF", "#C2001F"] },
];
